# -*- coding: utf-8 -*-
"""subsequentCreatinineRise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18o_aWgz9o_pIfaJNzNeg3iI5VDBV3Usz
"""

# Import Trifecta
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os
#os.listdir() // toy.txt

x = pd.read_csv('toy.txt', delimiter='\t')
x.head()

# Time formatting
x['time'] = pd.to_datetime(x.time)
x = x.set_index('time', drop = False)
maxCreat7d = x[::-1].groupby('mrn', as_index = False, sort = False)['creat'].rolling(pd.to_timedelta('7 days')).max()[::-1] # Max creatinine w/ 7-day lookforward
x = x.set_index(['mrn', 'time'])
x['subsRise'] = x['creat'] <= maxCreat7d
x.head()

# Import Trifecta
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os
#os.listdir() // toy.txt

# Time formatting
x['time'] = pd.to_datetime(x.time)
x = x.set_index('time', drop = False)

maxCreat7d = x[::-1].groupby('mrn', as_index = False, sort = False)['creat'].rolling(pd.to_timedelta('7 days')).max()[::-1] # Max creatinine w/ 7-day lookforward
x = x.set_index(['mrn', 'time'])
x['subsRise'] = x['creat'] <= maxCreat7d

x

